# yaml-language-server: $schema=../../settings.schema.json
schema_version: 1
upstream_env_url: "https://github.com/Sonarr/Sonarr"
ports:
  - port: 8989
    protocol: tcp
    required: false
env:
  - name: DOTNET_EnableDiagnostics
    default: "0"
    required: false
  - name: SONARR__SERVER__PORT
    default: "8989"
    required: false
  - name: SONARR__UPDATE__BRANCH
    default: "develop"
    required: false
volumes:
  - path: /config
    required: true
opt_dependencies:
  - image: postgresql
