# yaml-language-server: $schema=../../settings.schema.json
schema_version: 1
upstream_env_url: "https://github.com/renovate/renovate"
ports:
  []
env:
  []
volumes:
  - path: /config
    required: true
