# yaml-language-server: $schema=../../settings.schema.json
schema_version: 1
upstream_env_url: "https://github.com/sct/overseerr"
ports:
  - port: 5055
    protocol: tcp
    required: false
env:
  - name: NODE_OPTIONS
    default: "--max_old_space_size=2048"
    required: false
volumes:
  - path: /config
    required: true
