# yaml-language-server: $schema=../../settings.schema.json
schema_version: 1
upstream_env_url: ""
ports:
  - port: 4545
    protocol: tcp
    required: false
env:
  - name: WEBUI_PORTS
    default: "4545/tcp,4545/udp"
    required: false
volumes:
  - path: /config
    required: true
