# yaml-language-server: $schema=https://raw.githubusercontent.com/trueforge-org/forgetool/refs/heads/main/schemas/container-settings.schema.json
schema_version: 1
upstream_env_url: "https://foldingathome.org/"
ports:
  - port: 7396
    protocol: tcp
    required: false
env:
  - name: DEBIAN_FRONTEND
    default: "noninteractive"
    required: false
  - name: NVIDIA_DRIVER_CAPABILITIES
    default: "compute,video,utility"
    required: false
volumes:
  - path: /config
    required: true
