---
# Areas
- name: area/apps
  color: 0e8a16
- name: area/github
  color: 0e8a16
- name: area/mise
  color: 0e8a16
- name: area/renovate
  color: 0e8a16
# Semantic Types
- name: type/digest
  color: ffeC19
- name: type/patch
  color: ffeC19
- name: type/minor
  color: ff9800
- name: type/major
  color: f6412d
# Issues
- name: bug
  color: "B60205"
- name: enhancement
  color: "a2eeef"
- name: outdated
  color: "a2eeef"
# Uncategorized
- name: stale
  color: c5def5
