# yaml-language-server: $schema=https://raw.githubusercontent.com/trueforge-org/forgetool/refs/heads/main/schemas/container-settings.schema.json
schema_version: 1
upstream_env_url: "https://caddyserver.com"
ports:
  - port: 8080
    protocol: tcp
    required: false
  - port: 8443
    protocol: tcp
    required: false
env:
  []
volumes:
  - path: /config
    required: true
