# yaml-language-server: $schema=https://raw.githubusercontent.com/trueforge-org/forgetool/refs/heads/main/schemas/container-settings.schema.json
schema_version: 1
upstream_env_url: "https://github.com/Whisparr/Whisparr"
ports:
  - port: 6969
    protocol: tcp
    required: false
env:
  - name: TZ
    default: "Etc/UTC"
    required: false
  - name: UMASK
    default: "002"
    required: false
  - name: DB_TYPE
    default: "sqlite"
    required: false
  - name: DB_HOST
    default: "postgresql"
    required: false
  - name: DB_PORT
    default: "5432"
    required: false
  - name: DB_USER
    default: "MYPOSTGRESUSER"
    required: false
  - name: DB_PASSWORD
    default: "MYPOSTGRESPASSWORD"
    required: false
  - name: DB_DATABASE
    default: "MYPOSTGRESDB"
    required: false
  - name: DB_LOGSDB
    default: "MYPOSTGRESDB-log"
    required: false
volumes:
  - path: /config
    required: true
opt_dependencies:
  - name: postgresql
