# yaml-language-server: $schema=https://raw.githubusercontent.com/trueforge-org/forgetool/refs/heads/main/schemas/container-settings.schema.json
schema_version: 1
upstream_env_url: "https://github.com/Whisparr/Whisparr"
ports:
  - port: 6969
    protocol: tcp
    required: false
env:
  - name: COMPlus_EnableDiagnostics
    default: "0"
    required: false
  - name: WHISPARR__SERVER__PORT
    default: "6969"
    required: false
  - name: WHISPARR__UPDATE__BRANCH
    default: "eros"
    required: false
volumes:
  - path: /config
    required: true
opt_dependencies:
  - name: postgresql
