# yaml-language-server: $schema=https://raw.githubusercontent.com/trueforge-org/forgetool/refs/heads/main/schemas/container-settings.schema.json
schema_version: 1
upstream_env_url: "https://github.com/dgtlmoon/changedetection.io"
ports:
  - port: 5000
    protocol: tcp
    required: false
env:
  - name: BASE_URL
    default: ""
    required: false
  - name: PLAYWRIGHT_DRIVER_URL
    default: ""
    required: false
  - name: TZ
    default: "Etc/UTC"
    required: false
  - name: USE_X_SETTINGS_FILE
    default: ""
    required: false
volumes:
  - path: /config
    required: true
