#!/usr/bin/with-contenv bash
# shellcheck shell=bash

run_branding() {
  # intentional tabs in the heredoc
  cat <<-EOF | tee /run/branding /etc/s6-overlay/s6-rc.d/init-adduser/branding > /dev/null 2>&1
	───────────────────────────────────────

	      ██╗     ███████╗██╗ ██████╗
	      ██║     ██╔════╝██║██╔═══██╗
	      ██║     ███████╗██║██║   ██║
	      ██║     ╚════██║██║██║   ██║
	      ███████╗███████║██║╚██████╔╝
	      ╚══════╝╚══════╝╚═╝ ╚═════╝

	   Brought to you by linuxserver.io
	───────────────────────────────────────
	EOF
}

if [[ "${LSIO_FIRST_PARTY}" = "true" ]]; then
    run_branding
fi
