# yaml-language-server: $schema=https://raw.githubusercontent.com/trueforge-org/forgetool/refs/heads/main/schemas/container-settings.schema.json
schema_version: 1
upstream_env_url: "https://github.com/snapdrop/snapdrop"
ports:
  - port: 80
    protocol: tcp
    required: false
  - port: 443
    protocol: tcp
    required: false
  - port: 3000
    protocol: tcp
    required: false
env:
  - name: HOME
    default: "/app"
    required: false
  - name: NODE_ENV
    default: "production"
    required: false
volumes:
  - path: /config
    required: true
