# yaml-language-server: $schema=../../settings.schema.json
schema_version: 1
upstream_env_url: ""
ports:
  []
env:
  - name: NVIDIA_DRIVER_CAPABILITIES
    default: "compute,video,utility"
    required: false
volumes:
  - path: /config
    required: true
