# yaml-language-server: $schema=https://raw.githubusercontent.com/trueforge-org/forgetool/refs/heads/main/schemas/container-settings.schema.json
schema_version: 1
upstream_env_url: "https://pydio.com/"
ports:
  - port: 8080
    protocol: tcp
    required: false
env:
  - name: TZ
    default: "Etc/UTC"
    required: false
  - name: EXTERNALURL
    default: "https://localhost:8080"
    required: false
  - name: SERVER_IP
    default: "0.0.0.0"
    required: false
volumes:
  - path: /config
    required: true
