# yaml-language-server: $schema=https://raw.githubusercontent.com/trueforge-org/forgetool/refs/heads/main/schemas/container-settings.schema.json
schema_version: 1
upstream_env_url: "https://oss.oetiker.ch/smokeping/"
ports:
  - port: 80
    protocol: tcp
    required: false
env:
  - name: MASTER_URL
    default: ""
    required: false
  - name: SHARED_SECRET
    default: ""
    required: false
  - name: TZ
    default: "Etc/UTC"
    required: false
volumes:
  - path: /config
    required: true
  - path: /data
    required: false
