# yaml-language-server: $schema=../../settings.schema.json
schema_version: 1
upstream_env_url: ""
ports:
  - port: 5514
    protocol: udp
    required: false
  - port: 6514
    protocol: tcp
    required: false
  - port: 6601
    protocol: tcp
    required: false
env:
  []
volumes:
  - path: /config
    required: true
