# yaml-language-server: $schema=https://raw.githubusercontent.com/trueforge-org/forgetool/refs/heads/main/schemas/container-settings.schema.json
schema_version: 1
upstream_env_url: "https://github.com/Lidarr/Lidarr"
ports:
  - port: 8686
    protocol: tcp
    required: false
env:
  - name: DOTNET_EnableDiagnostics
    default: "0"
    required: false
  - name: LIDARR__SERVER__PORT
    default: "8686"
    required: false
  - name: LIDARR__UPDATE__BRANCH
    default: "develop"
    required: false
volumes:
  - path: /config
    required: true
opt_dependencies:
  - image: postgresql
