# yaml-language-server: $schema=../../settings.schema.json
schema_version: 1
upstream_env_url: ""
ports:
  []
env:
  - name: DOTNET_EnableDiagnostics
    default: "0"
    required: false
  - name: LIDARR__SERVER__PORT
    default: "8686"
    required: false
  - name: LIDARR__UPDATE__BRANCH
    default: "develop"
    required: false
volumes:
  - path: /config
    required: true
