# yaml-language-server: $schema=../../settings.schema.json
schema_version: 1
upstream_env_url: "https://www.openssh.com/"
ports:
  - port: 2222
    protocol: tcp
    required: false
env:
  []
volumes:
  - path: /config
    required: true
