# yaml-language-server: $schema=https://raw.githubusercontent.com/trueforge-org/forgetool/refs/heads/main/schemas/container-settings.schema.json
schema_version: 1
upstream_env_url: "https://hub.docker.com/_/node"
ports:
  []
env:
  []
volumes:
  - path: /config
    required: true
