# yaml-language-server: $schema=../../settings.schema.json
schema_version: 1
upstream_env_url: "https://github.com/tailscale/tailscale"
ports:
  []
env:
  []
volumes:
  - path: /config
    required: true
  - path: /var/lib/tailscale
    required: false
