# yaml-language-server: $schema=../../settings.schema.json
schema_version: 1
upstream_env_url: "https://coder.com"
ports:
  - port: 8443
    protocol: tcp
    required: false
env:
  - name: HOME
    default: "/config"
    required: false
volumes:
  - path: /config
    required: true
