# yaml-language-server: $schema=../../settings.schema.json
schema_version: 1
upstream_env_url: "https://github.com/healthchecks/healthchecks"
ports:
  - port: 8000
    protocol: tcp
    required: false
env:
  - name: PYTHONUNBUFFERED
    default: "1"
    required: false
volumes:
  - path: /config
    required: true
