# yaml-language-server: $schema=../../settings.schema.json
schema_version: 1
upstream_env_url: "https://github.com/trueforge-org/drydock"
ports:
  - port: 3000
    protocol: tcp
    required: false
env:
  - name: DD_LOG_FORMAT
    default: "text"
    required: false
  - name: DD_STORE_PATH
    default: "/config"
    required: false
  - name: DD_VERSION
    default: "$VERSION"
    required: false
  - name: WORKDIR
    default: "/app"
    required: false
volumes:
  - path: /config
    required: true
