# yaml-language-server: $schema=https://raw.githubusercontent.com/trueforge-org/forgetool/refs/heads/main/schemas/container-settings.schema.json
schema_version: 1
upstream_env_url: "https://valkey.io"
ports:
  - port: 6379
    protocol: tcp
    required: false
env:
  - name: TZ
    default: "Etc/UTC"
    required: false
  - name: VALKEY_PASSWORD
    default: "MYVALKEYPASSWORD"
    required: false
volumes:
  - path: /config
    required: true
