# yaml-language-server: $schema=../../settings.schema.json
schema_version: 1
upstream_env_url: ""
ports:
  - port: 6379
    protocol: tcp
    required: false
env:
  - name: VALKEY_PORT
    default: "6379"
    required: false
volumes:
  - path: /config
    required: true
