# yaml-language-server: $schema=https://raw.githubusercontent.com/trueforge-org/forgetool/refs/heads/main/schemas/container-settings.schema.json
schema_version: 1
upstream_env_url: "https://mariadb.org/"
ports:
  - port: 3306
    protocol: tcp
    required: false
env:
  - name: DATADIR
    default: "$MYSQL_DIR/databases"
    required: false
  - name: MYSQL_DIR
    default: "/config"
    required: false
volumes:
  - path: /config
    required: true
