# yaml-language-server: $schema=../../settings.schema.json
schema_version: 1
upstream_env_url: "https://github.com/sabnzbd/sabnzbd"
ports:
  - port: 8080
    protocol: tcp
    required: false
env:
  - name: SABNZBD__ADDRESS
    default: "[::]"
    required: false
  - name: SABNZBD__PORT
    default: "8080"
    required: false
volumes:
  - path: /config
    required: true
