---
name: "🐛 Bug Report"
description: "Report an issue with a container/image build, Dockerfile, or runtime behavior."
title: "[BUG] "
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: "Describe the bug clearly. Include which container/image is affected."
      placeholder: "e.g., The container fails to start when using image xyz:1.0"
    validations:
      required: true

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: "Steps to Reproduce"
      description: "Step by step instructions to reproduce the issue"
      placeholder: "1. docker run xyz:1.0\n2. Observe logs"
    validations:
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: "Expected Behavior"
      description: "What you expected to happen"
      placeholder: "The container should start successfully"
    validations:
      required: true

  - type: textarea
    id: actual_behavior
    attributes:
      label: "Actual Behavior"
      description: "What actually happened"
      placeholder: "The container crashes with exit code 1"
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: "Environment"
      description: "Container/image, tag, OS, Docker version, and other relevant info"
      placeholder: "- Container/Image: xyz\n- Tag/Version: 1.0\n- OS: Ubuntu 22.04\n- Docker Version: 24.0"
    validations:
      required: true

  - type: checkboxes
    id: terms
    attributes:
      label: "I've read and agree with the following"
      options:
        - label: "I've checked all open and closed issues and my issue is not there."
          required: true