# yaml-language-server: $schema=../../settings.schema.json
schema_version: 1
upstream_env_url: "https://github.com/babybuddy/babybuddy"
ports:
  - port: 8000
    protocol: tcp
    required: false
env:
  - name: S6_STAGE2_HOOK
    default: "/init-hook"
    required: false
volumes:
  - path: /config
    required: true
opt_dependencies:
  - image: postgresql
  - image: mariadb
