# yaml-language-server: $schema=../../settings.schema.json
schema_version: 1
upstream_env_url: ""
ports:
  []
env:
  - name: COMPlus_EnableDiagnostics
    default: "0"
    required: false
  - name: READARR__SERVER__PORT
    default: "8787"
    required: false
  - name: READARR__UPDATE__BRANCH
    default: "develop"
    required: false
volumes:
  - path: /config
    required: true
