# yaml-language-server: $schema=https://raw.githubusercontent.com/trueforge-org/forgetool/refs/heads/main/schemas/container-settings.schema.json
schema_version: 1
upstream_env_url: "https://github.com/diskoverdata/diskover-community"
ports:
  - port: 80
    protocol: tcp
    required: false
  - port: 443
    protocol: tcp
    required: false
env:
  - name: ES_HOST
    default: "elasticsearch"
    required: false
  - name: ES_PASS
    default: ""
    required: false
  - name: ES_USER
    default: "elastic"
    required: false
  - name: TZ
    default: "Etc/UTC"
    required: false
volumes:
  - path: /config
    required: true
