# yaml-language-server: $schema=https://raw.githubusercontent.com/trueforge-org/forgetool/refs/heads/main/schemas/container-settings.schema.json
schema_version: 1
upstream_env_url: "https://hub.docker.com/_/nginx"
ports:
  - port: 8080
    protocol: tcp
    required: false
  - port: 8443
    protocol: tcp
    required: false
env:
  - name: NGINX_PORT
    default: "8080"
    required: false
  - name: TZ
    default: "Etc/UTC"
    required: false
volumes:
  - path: /config
    required: true
