# yaml-language-server: $schema=../../settings.schema.json
schema_version: 1
upstream_env_url: ""
ports:
  []
env:
  - name: DOTNET_EnableDiagnostics
    default: "0"
    required: false
  - name: PROWLARR__SERVER__PORT
    default: "9696"
    required: false
  - name: PROWLARR__UPDATE__BRANCH
    default: "develop"
    required: false
volumes:
  - path: /config
    required: true
