# yaml-language-server: $schema=../../settings.schema.json
schema_version: 1
upstream_env_url: ""
ports:
  []
env:
  - name: HOME
    default: "/config"
    required: false
  - name: TRANSMISSION_WEB_HOME
    default: "/usr/share/transmission/public_html"
    required: false
  - name: XDG_CONFIG_HOME
    default: "/config"
    required: false
  - name: XDG_DATA_HOME
    default: "/config"
    required: false
volumes:
  - path: /config
    required: true
