# yaml-language-server: $schema=../../settings.schema.json
schema_version: 1
upstream_env_url: "https://memcached.org"
ports:
  - port: 11211
    protocol: tcp
    required: false
env:
  []
volumes:
  - path: /config
    required: true
