# yaml-language-server: $schema=../../settings.schema.json
schema_version: 1
upstream_env_url: "https://github.com/sickgear/sickgear"
ports:
  - port: 8081
    protocol: tcp
    required: false
env:
  - name: PYTHONIOENCODING
    default: "UTF-8"
    required: false
volumes:
  - path: /config
    required: true
