# yaml-language-server: $schema=../../settings.schema.json
schema_version: 1
upstream_env_url: "https://github.com/morpheus65535/bazarr"
ports:
  - port: 6767
    protocol: tcp
    required: false
env:
  - name: BAZARR_PACKAGE_AUTHOR
    default: "${VENDOR}"
    required: false
  - name: BAZARR_PACKAGE_VERSION
    default: "${VERSION}"
    required: false
  - name: BAZARR_VERSION
    default: "${VERSION}"
    required: false
  - name: BAZARR__PORT
    default: "6767"
    required: false
volumes:
  - path: /config
    required: true
