# yaml-language-server: $schema=https://raw.githubusercontent.com/trueforge-org/forgetool/refs/heads/main/schemas/container-settings.schema.json
schema_version: 1
upstream_env_url: "https://github.com/BookStackApp/BookStack"
ports:
  - port: 80
    protocol: tcp
    required: false
  - port: 443
    protocol: tcp
    required: false
env:
  - name: TZ
    default: "Etc/UTC"
    required: false
  - name: APP_URL
    default: ""
    required: true
  - name: APP_KEY
    default: ""
    required: true
  - name: DB_HOST
    default: ""
    required: true
  - name: DB_PORT
    default: "3306"
    required: false
  - name: DB_USER
    default: "MYMARIADBUSER"
    required: true
  - name: DB_PASS
    default: "MYMARIADBPASSWORD"
    required: false
  - name: DB_DATABASE
    default: "MYMARIADBDB"
    required: false
volumes:
  - path: /config
    required: true
opt_dependencies:
  - name: mariadb
