# yaml-language-server: $schema=https://raw.githubusercontent.com/trueforge-org/forgetool/refs/heads/main/schemas/container-settings.schema.json
schema_version: 1
upstream_env_url: "https://github.com/qbittorrent/qBittorrent"
ports:
  - port: 6881
    protocol: tcp
    required: false
  - port: 6881
    protocol: udp
    required: false
  - port: 8080
    protocol: tcp
    required: false
env:
  - name: QBT_WEBUI_PORT
    default: "8080"
    required: false
  - name: TZ
    default: "Etc/UTC"
    required: false
  - name: UMASK
    default: "002"
    required: false
volumes:
  - path: /config
    required: true
