# yaml-language-server: $schema=https://raw.githubusercontent.com/trueforge-org/forgetool/refs/heads/main/schemas/container-settings.schema.json
schema_version: 1
upstream_env_url: "https://www.steamdeck.com/"
ports:
  - port: 3000
    protocol: tcp
    required: false
env:
  - name: TZ
    default: "Etc/UTC"
    required: false
  - name: TITLE
    default: "SteamOS"
    required: false
  - name: RESOLUTION
    default: "1280x720"
    required: false
  - name: DRINODE
    default: ""
    required: false
  - name: HW3D
    default: "false"
    required: false
  - name: DISABLE_DRI
    default: "false"
    required: false
volumes:
  - path: /config
    required: true
