# yaml-language-server: $schema=../../settings.schema.json
schema_version: 1
upstream_env_url: "https://github.com/alexjustesen/speedtest-tracker"
ports:
  []
env:
  - name: HOME
    default: "/config"
    required: false
volumes:
  - path: /config
    required: true
