# yaml-language-server: $schema=../../settings.schema.json
schema_version: 1
upstream_env_url: ""
ports:
  - port: 6501
    protocol: tcp
    required: false
env:
  - name: MAKEFLAGS
    default: "-j4"
    required: false
volumes:
  - path: /config
    required: true
