# yaml-language-server: $schema=https://raw.githubusercontent.com/trueforge-org/forgetool/refs/heads/main/schemas/container-settings.schema.json
schema_version: 1
upstream_env_url: "https://hedgedoc.org/"
ports:
  - port: 3000
    protocol: tcp
    required: false
env:
  - name: CMD_ALLOW_ANONYMOUS
    default: "true"
    required: false
  - name: CMD_ALLOW_FREEURL
    default: "false"
    required: false
  - name: CMD_DOMAIN
    default: ""
    required: false
  - name: CMD_PROTOCOL_USESSL
    default: "false"
    required: false
  - name: CMD_SESSION_SECRET
    default: ""
    required: false
  - name: CMD_URL_ADDPORT
    default: "false"
    required: false
  - name: TZ
    default: "Etc/UTC"
    required: false
  - name: DB_HOST
    default: "postgresql"
    required: true
  - name: DB_PORT
    default: "5432"
    required: true
  - name: DB_USER
    default: "MYPOSTGRESUSER"
    required: true
  - name: DB_PASS
    default: "MYPOSTGRESPASSWORD"
    required: true
  - name: DB_NAME
    default: "MYPOSTGRESDB"
    required: true
  - name: CMD_DB_DIALECT
    default: "postgres"
    required: true
volumes:
  - path: /config
    required: true
dependencies:
  - name: postgresql
