# yaml-language-server: $schema=../../settings.schema.json
schema_version: 1
upstream_env_url: "https://hedgedoc.org/"
ports:
  - port: 3000
    protocol: tcp
    required: false
env:
  - name: NODE_ENV
    default: "production"
    required: false
  - name: PUPPETEER_SKIP_DOWNLOAD
    default: "true"
    required: false
  - name: YARN_CACHE_FOLDER
    default: "/tmp/.yarn"
    required: false
volumes:
  - path: /config
    required: true
dependencies:
  - postgresql
