# yaml-language-server: $schema=https://raw.githubusercontent.com/trueforge-org/forgetool/refs/heads/main/schemas/container-settings.schema.json
schema_version: 1
upstream_env_url: "https://github.com/netbox-community/netbox"
ports:
  - port: 8000
    protocol: tcp
    required: false
env:
  - name: ALLOWED_HOSTS
    default: "*"
    required: false
  - name: SECRET_KEY
    default: ""
    required: true
  - name: SUPERUSER_EMAIL
    default: ""
    required: false
  - name: SUPERUSER_NAME
    default: "admin"
    required: false
  - name: SUPERUSER_PASSWORD
    default: "MYSUPERUSERPASSWORD"
    required: false
  - name: TZ
    default: "Etc/UTC"
    required: false
  - name: DB_HOST
    default: "postgresql"
    required: true
  - name: DB_PORT
    default: "5432"
    required: true
  - name: DB_NAME
    default: "MYPOSTGRESDB"
    required: true
  - name: DB_USER
    default: "MYPOSTGRESUSER"
    required: true
  - name: DB_PASSWORD
    default: "MYPOSTGRESPASSWORD"
    required: true
  - name: REDIS_HOST
    default: "valkey"
    required: true
  - name: REDIS_PORT
    default: "6379"
    required: true
  - name: REDIS_PASSWORD
    default: "MYVALKEYPASSWORD"
    required: true
  - name: REDIS_DB_TASK
    default: "0"
    required: false
  - name: REDIS_DB_CACHE
    default: "1"
    required: false
volumes:
  - path: /config
    required: true
dependencies:
  - name: postgresql
  - name: valkey
