# yaml-language-server: $schema=../../settings.schema.json
schema_version: 1
upstream_env_url: "https://github.com/CorentinTh/it-tools"
ports:
  - port: 8080
    protocol: tcp
    required: false
env:
  - name: HOME
    default: "/tmp"
    required: false
volumes:
  - path: /config
    required: true
