
FROM ghcr.io/linuxserver/baseimage-alpine:arm64v8-3.22

# set version label
ARG VERSION

RUN \
  echo "**** install build packages ****" && \
  YQ_VERSION=v4.45.1 &&\
  wget https://github.com/mikefarah/yq/releases/download/${YQ_VERSION}/yq_linux_arm64 -O /usr/bin/yq &&\
  chmod +x /usr/bin/yq && \
  apk add --no-cache --upgrade \
    ansible && \
  apk del \
    alpine-release

COPY /ansible /app
COPY entrypoint.sh entrypoint.sh

WORKDIR /app

ENTRYPOINT ["catatonit", "--", "/entrypoint.sh"]
