# yaml-language-server: $schema=https://raw.githubusercontent.com/trueforge-org/forgetool/refs/heads/main/schemas/container-settings.schema.json
schema_version: 1
upstream_env_url: "https://github.com/Tautulli/Tautulli"
ports:
  - port: 8181
    protocol: tcp
    required: false
env:
  - name: TAUTULLI_DOCKER
    default: "True"
    required: false
volumes:
  - path: /config
    required: true
