# yaml-language-server: $schema=../../settings.schema.json
schema_version: 1
upstream_env_url: "https://thelounge.github.io/"
ports:
  - port: 9000
    protocol: tcp
    required: false
env:
  - name: THELOUNGE_HOME
    default: "/config"
    required: false
volumes:
  - path: /config
    required: true
