# yaml-language-server: $schema=../../settings.schema.json
schema_version: 1
upstream_env_url: "https://github.com/seerr-team/seerr"
ports:
  - port: 5055
    protocol: tcp
    required: false
env:
  []
volumes:
  - path: /config
    required: true
