# yaml-language-server: $schema=https://raw.githubusercontent.com/trueforge-org/forgetool/refs/heads/main/schemas/container-settings.schema.json
schema_version: 1
upstream_env_url: "https://postgresql.org"
ports:
  - port: 5432
    protocol: tcp
    required: false
env:
  - name: LANG
    default: "en_US.UTF-8"
    required: false
  - name: LC_ALL
    default: "en_US.UTF-8"
    required: false
  - name: PATH
    default: "/usr/lib/postgresql/${PG_MAJOR}/bin:$PATH"
    required: false
  - name: PGDATA
    default: "/config/$PG_MAJOR"
    required: false
  - name: PG_MAJOR
    default: "$PG_MAJOR"
    required: false
volumes:
  - path: /config
    required: true
