# yaml-language-server: $schema=https://raw.githubusercontent.com/trueforge-org/forgetool/refs/heads/main/schemas/container-settings.schema.json
schema_version: 1
upstream_env_url: "https://github.com/caronc/apprise-api"
ports:
  - port: 8000
    protocol: tcp
    required: false
env:
  - name: APPRISE_ATTACH_DIR
    default: "/attachments"
    required: false
  - name: APPRISE_ATTACH_SIZE
    default: "0"
    required: false
  - name: APPRISE_CONFIG_DIR
    default: "/config"
    required: false
volumes:
  - path: /config
    required: true
