# yaml-language-server: $schema=https://raw.githubusercontent.com/trueforge-org/forgetool/refs/heads/main/schemas/container-settings.schema.json
schema_version: 1
upstream_env_url: "https://www.kasmweb.com/"
ports:
  - port: 3000
    protocol: tcp
    required: false
  - port: 443
    protocol: tcp
    required: false
env:
  - name: TZ
    default: "Etc/UTC"
    required: false
  - name: DOCKER_HUB_USERNAME
    default: ""
    required: false
  - name: DOCKER_HUB_PASSWORD
    default: ""
    required: false
volumes:
  - path: /config
    required: true
  - path: /opt
    required: false
