# yaml-language-server: $schema=../../settings.schema.json
schema_version: 1
upstream_env_url: ""
ports:
  - port: 8000
    protocol: tcp
    required: false
  - port: 8443
    protocol: tcp
    required: false
env:
  - name: HOME
    default: "/config"
    required: false
volumes:
  - path: /config
    required: true
  - path: /storage
    required: false
