# yaml-language-server: $schema=https://raw.githubusercontent.com/trueforge-org/forgetool/refs/heads/main/schemas/container-settings.schema.json
schema_version: 1
upstream_env_url: "https://vaemendis.net/ubooquity/"
ports:
  - port: 2202
    protocol: tcp
    required: false
  - port: 2203
    protocol: tcp
    required: false
env:
  - name: TZ
    default: "Etc/UTC"
    required: false
  - name: MAXMEM
    default: "512"
    required: false
volumes:
  - path: /config
    required: true
