# yaml-language-server: $schema=https://raw.githubusercontent.com/trueforge-org/forgetool/refs/heads/main/schemas/container-settings.schema.json
schema_version: 1
upstream_env_url: "https://github.com/adnanh/webhook"
ports:
  - port: 9000
    protocol: tcp
    required: false
env:
  - name: WEBHOOK__PORT
    default: "9000"
    required: false
  - name: WEBHOOK__URLPREFIX
    default: "hooks"
    required: false
volumes:
  - path: /config
    required: true
