# yaml-language-server: $schema=https://raw.githubusercontent.com/trueforge-org/forgetool/refs/heads/main/schemas/container-settings.schema.json
schema_version: 1
upstream_env_url: "https://github.com/blacktwin/JBOPS"
ports:
  []
env:
  - name: JBOPS__SCRIPT_PATH
    default: "fun/plexapi_haiku.py"
    required: false
  - name: PLEXAPI_CONFIG_PATH
    default: "/config/config.ini"
    required: false
volumes:
  - path: /config
    required: true
