# yaml-language-server: $schema=https://raw.githubusercontent.com/trueforge-org/forgetool/refs/heads/main/schemas/container-settings.schema.json
schema_version: 1
upstream_env_url: "https://github.com/grokability/snipe-it"
ports:
  - port: 80
    protocol: tcp
    required: false
  - port: 443
    protocol: tcp
    required: false
env:
  - name: APP_KEY
    default: ""
    required: true
  - name: APP_LOCALE
    default: "en"
    required: false
  - name: APP_TIMEZONE
    default: "UTC"
    required: false
  - name: APP_URL
    default: ""
    required: false
  - name: TZ
    default: "Etc/UTC"
    required: false
  - name: DB_CONNECTION
    default: "mysql"
    required: true
  - name: DB_HOST
    default: "mariadb"
    required: true
  - name: DB_PORT
    default: "3306"
    required: true
  - name: DB_DATABASE
    default: "MYMARIADBDB"
    required: true
  - name: DB_USERNAME
    default: "MYMARIADBUSER"
    required: true
  - name: DB_PASSWORD
    default: "MYMARIADBPASSWORD"
    required: true
volumes:
  - path: /config
    required: true
dependencies:
  - name: mariadb
