# yaml-language-server: $schema=https://raw.githubusercontent.com/trueforge-org/forgetool/refs/heads/main/schemas/container-settings.schema.json
schema_version: 1
upstream_env_url: "https://github.com/esphome/esphome"
ports:
  - port: 6052
    protocol: tcp
    required: false
env:
  - name: ESPHOME_BUILD_PATH
    default: "/cache/build"
    required: false
  - name: ESPHOME_DATA_DIR
    default: "/cache/data"
    required: false
  - name: HOME
    default: "/config"
    required: false
  - name: PLATFORMIO_CORE_DIR
    default: "/cache/pio"
    required: false
volumes:
  - path: /config
    required: true
