# yaml-language-server: $schema=../../settings.schema.json
schema_version: 1
upstream_env_url: "https://github.com/Kareadita/Kavita"
ports:
  - port: 5000
    protocol: tcp
    required: false
env:
  - name: COMPlus_EnableDiagnostics
    default: "0"
    required: false
  - name: HOME
    default: "/config"
    required: false
volumes:
  - path: /config
    required: true
