# yaml-language-server: $schema=https://raw.githubusercontent.com/trueforge-org/forgetool/refs/heads/main/schemas/container-settings.schema.json
schema_version: 1
upstream_env_url: "https://github.com/prometheus-community/smartctl_exporter"
ports:
  - port: 9633
    protocol: tcp
    required: false
env:
  - name: SMARTCTL_EXPORTER_LOG_LEVEL
    default: "info"
    required: false
volumes:
  - path: /config
    required: true
