# yaml-language-server: $schema=../../settings.schema.json
schema_version: 1
upstream_env_url: "https://github.com/SergiX44/XBackBone"
ports:
  - port: 80
    protocol: tcp
    required: false
  - port: 443
    protocol: tcp
    required: false
env:
  []
volumes:
  - path: /config
    required: true
