---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Renovate

on:
  push:
    branches:
      - main
    paths:
      - .renovaterc.json5
      - .renovate/**.json5
  workflow_dispatch:

jobs:
  renovate:
    name: Renovate
    runs-on:
      group: default
    steps:
      - name: Generate Token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        id: app-token
        with:
          app-id: ${{ secrets.BOT_APP_ID }}
          private-key: ${{ secrets.BOT_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Run Renovate
        uses: codex-/return-dispatch@85e564d60eaec3cc4aca885373d510cfe4bd5b19 # v4.0.1
        id: dispatch
        with:
          token: ${{ steps.app-token.outputs.token }}
          owner: ${{ github.repository_owner }}
          repo: .github
          ref: main
          workflow: renovate.yaml
          workflow_inputs: |-
            { "autodiscoverFilter": "${{ github.event.repository.name }}" }

      - name: Await Renovate Completion
        uses: Codex-/await-remote-run@bb04140a0965ec5532845d826a74dc5f075f891b # v3.0.0
        with:
          token: ${{ steps.app-token.outputs.token }}
          owner: ${{ github.repository_owner }}
          repo: .github
          run_id: ${{ steps.dispatch.outputs.run_id }}

      - name: Renovate Output
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |-
          gh run view --repo ${{ github.repository_owner }}/.github --log ${{ steps.dispatch.outputs.run_id }}
